{% set name = "syrupy" %}
{% set version = "5.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/syrupy-{{ version }}.tar.gz
  sha256: 3282fe963fa5d4d3e47231b16d1d4d0f4523705e8199eeb99a22a1bc9f5942f2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core >=1.4.0
  run:
    - python >={{ python_min }},<4.0
    - pytest >=7.0.0,<9.0.0

test:
  imports:
    - syrupy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/syrupy-project/syrupy
  summary: Pytest Snapshot Test Utility
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - noahnu
    - ludaavics
