{% set name = "syrupy" %}
{% set version = "5.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/syrupy-{{ version }}.tar.gz
  sha256: 42fca95ebf5cc376095b4eb5dd142b10146f08731ed676c3f3b7c9421bf56804

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }},<4.0
    - pytest >=8.0.0

test:
  imports:
    - syrupy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/syrupy-project/syrupy
  summary: Pytest Snapshot Test Utility
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - noahnu
    - ludaavics
