{% set name = "syrupy" %}
{% set version = "5.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/syrupy-{{ version }}.tar.gz
  sha256: 10f192655a2d42473ad5772653e64b281f6823fe5e30458d92f8ca8e882884c1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }},<4.0
    - pytest >=8.0.0

test:
  imports:
    - syrupy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/syrupy-project/syrupy
  summary: Pytest Snapshot Test Utility
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - noahnu
    - ludaavics
