{% set name = "syrupy" %}
{% set version = "4.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/syrupy-{{ version }}.tar.gz
  sha256: 806195794ed4fc17bec2836dd94f52b037fdb136e7c11949633e3970096ffec6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8.1,<4.0
    - pip
    - poetry-core >=1.3.2
  run:
    - python >=3.8.1,<4.0
    - colored >=1.3.92,<2.0.0
    - pytest >=7.0.0,<8.0.0

test:
  imports:
    - syrupy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tophat/syrupy
  summary: Pytest Snapshot Test Utility
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - noahnu
    - ludaavics
